name: Install FFmpeg

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FFmpeg
      run: sudo apt update && sudo apt install -y ffmpeg
